### ISSUE TITLE
File name is not displayed for fileUpload field

### ISSUE THREAD

**Issue by lovtsovaik** [Haulmont/jmix-localfs#4]
Jmix platform version: 0.3.0-SNAPSHOT

1. Create an entity with byte[] attribute
2. Create browser and editor screen
3. Add `showFileName="true"` to `fileUpload` field in editor
4. Create liquibase changelog, update database, run app
5. Open browser
6. Click Create button
7. Upload file

AR: file name is not displayed
![image.png](https://images.zenhubusercontent.com/5f928f98512e55007e6435dc/c59865b0-911d-4bc7-8b07-495251a0e023)
ER: display name if attribute showFileName="true"

**Comment by glebshalyganov** [comment]
`FileUploadField` saves an array of bytes, which doesn't have a "name". Displayed name can be set manually via `FileUploadField#setFileName` method. Otherwise, a general `attachment (N kb)` name will be displayed.
So it is a correct behaviour. The only thing is that perhaps `showFileName` parameter is a little bit confusing.
